// OWNED_BY: generic. Production code under synthetic failure and recovery tests.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function ctx(extra={}){const main={innerHTML:''};const c={console:{warn(){},error(){}},URLSearchParams,setTimeout,clearTimeout,AbortController,location:{hostname:'tech.example.invalid',search:''},document:{body:{classList:{toggle(){},contains(){return false}}},querySelectorAll:()=>[],getElementById:id=>id==='main-content'?main:null},localStorage:{getItem:()=>''},getUserRole:()=> 'super_admin',...extra};c.window=c;vm.createContext(c);return {c,main};}
const tick=()=>new Promise(r=>setImmediate(r));
test('async module rejection renders an escaped, recoverable error',async()=>{const {c,main}=ctx({renderDashboard:async()=>{throw Error('<img src=x onerror=alert(1)>')}});vm.runInContext(fs.readFileSync('ava-platform/js/core/router.js','utf8'),c);await c.navigate('dashboard');await tick();assert.match(main.innerHTML,/Gagal Memuat/);assert.match(main.innerHTML,/&lt;img/);assert.doesNotMatch(main.innerHTML,/<img/);assert.match(main.innerHTML,/Muat Ulang/)});
test('late module rejection cannot replace a newer route',async()=>{let reject;const {c,main}=ctx({renderDashboard:()=>new Promise((_,r)=>{reject=r}),renderPartners:()=>{main.innerHTML='Partners ready'}});vm.runInContext(fs.readFileSync('ava-platform/js/core/router.js','utf8'),c);await c.navigate('dashboard');await c.navigate('partners');reject(Error('old page'));await tick();assert.equal(main.innerHTML,'Partners ready')});
test('failed lazy load is evicted and navigation can retry',async()=>{let attempts=0;const {c}=ctx({document:{createElement:()=>({remove(){}}),head:{appendChild(s){attempts++;queueMicrotask(()=>attempts===1?s.onerror():s.onload())}}}});vm.runInContext(fs.readFileSync('ava-platform/js/core/lazy.js','utf8'),c);await assert.rejects(c.muatSkrip('module.js'));await c.muatSkrip('module.js');await c.muatSkrip('module.js');assert.equal(attempts,2)});
test('tenant chart distinguishes unavailable, empty and real status counts',()=>{const {c}=ctx();vm.runInContext(fs.readFileSync('ava-platform/modules/tech-platform/tech_saas.js','utf8'),c);assert.match(c.tsTenantSummary(null),/belum dapat dimuat/);assert.match(c.tsTenantSummary([]),/Belum ada tenant/);const html=c.tsTenantSummary([{kode:'a',is_active:true,status_langganan:'aktif'},{kode:'b',is_active:false,status_langganan:'kedaluwarsa'},{kode:'c',is_active:false,status_langganan:'aktif'}]);assert.match(html,/total 3 tenant/);assert.equal((html.match(/<strong>1 /g)||[]).length,3);assert.doesNotMatch(html,/28 Agu|27 Sep/)});
test('tenant read errors remain unavailable, not zero tenants',async()=>{const {c}=ctx({sbGetStrict:async()=>{throw Error('offline')}});vm.runInContext(fs.readFileSync('ava-platform/modules/tech-platform/tech_saas.js','utf8'),c);assert.equal(await c.tsAmbilTenant(),null)});
test('timeline and license modules coexist in the same browser scope',()=>{const {c}=ctx();vm.runInContext(fs.readFileSync('ava-platform/modules/system/timeline.js','utf8'),c);assert.doesNotThrow(()=>vm.runInContext(fs.readFileSync('ava-platform/modules/tech-platform/techLicenseActivation.js','utf8'),c));assert.equal(typeof c.renderTechLicenseActivation,'function')});
test('executive data loads without the task management module',async()=>{const {c}=ctx({sbGet:async()=>[]});vm.runInContext(fs.readFileSync('ava-platform/modules/dashboard/executive_dashboard.js','utf8'),c);await c.loadExecData()});
test('settings counts read aggregate count, not response row length; offline stays unknown',async()=>{const el={innerHTML:'',classList:{remove(){}}};const {c}=ctx({document:{getElementById:()=>el},sbGetStrict:async t=>t==='partners'?[{count:42}]:null});vm.runInContext(fs.readFileSync('ava-platform/modules/system/settings.js','utf8'),c);await c.loadSetStats();assert.match(el.innerHTML,/>42</);assert.match(el.innerHTML,/>—</);assert.doesNotMatch(el.innerHTML,/>1</)});
test('connection check fails honestly when backend is unavailable',async()=>{const el={};const {c}=ctx({document:{getElementById:()=>el},sbGetStrict:async()=>{throw Error('Unavailable')}});vm.runInContext(fs.readFileSync('ava-platform/modules/system/settings.js','utf8'),c);await c.checkSetConn();assert.equal(el.className,'status-box status-err');assert.doesNotMatch(el.textContent,/normal/)});
