// OWNED_BY: generic. Real episode and clinical SQL; no production data.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),f=require('../lib/care-episodes-fixture.cjs');let pg,n=0,error,closed=false;const results=[],key=()=>`synthetic-care-${++n}`;
async function q(sql,args=[]){return(await pg.query(sql,args)).rows;}
async function rpc(name,args){return(await q(`SELECT ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) r`,args))[0].r;}
async function actor(id=f.admin,tenant=f.A,role='super_admin'){await q('UPDATE user_profiles SET role=$1 WHERE id=$2',[role,id]);await q("SELECT set_config('app.user_id',$1,false),set_config('app.tenant_id',$2,false)",[id,tenant]);}
async function policy(kind,scope,payload){await actor();let p=await rpc('ops_policy_command',[null,'create',JSON.stringify({kind,scope,payload,reason:'Synthetic setup'}),key()]);p=await rpc('ops_policy_command',[p.id,'submit',JSON.stringify({expected_state:'draft',reason:'Synthetic submit'}),key()]);await actor(f.receiver,f.A,'dokter');p=await rpc('ops_policy_command',[p.id,'approve',JSON.stringify({expected_state:'in_review',reason:'Synthetic approve'}),key()]);await actor();return rpc('ops_policy_command',[p.id,'activate',JSON.stringify({expected_state:'approved',effective_at:new Date().toISOString(),reason:'Synthetic activate'}),key()]);}
const cmd=(action,data,k=key())=>rpc('rs_episode_command',[action,JSON.stringify({reason:'Synthetic care operation',...data}),k]);
const step=(ep,action,data={})=>cmd(action,{id:ep.id,version:ep.version,...data});
async function clinical(scope,admission,values){await actor(f.worker,f.A,'dokter');const p=(await q("SELECT id FROM ops_policy_versions WHERE kind='clinical_template' AND scope=$1 AND state='active'",[scope]))[0];let c=await rpc('rs_clinical_command',['record',JSON.stringify({admission_id:admission,policy_id:p.id,values,reason:'Synthetic clinical decision'}),key()]);return rpc('rs_clinical_command',['sign',JSON.stringify({id:c.id,reason:'Synthetic professional signature'}),key()]);}
async function check(name,fn){await fn();results.push({name,status:'passed'});console.log('PASS '+name);}
(async()=>{try{pg=await f.createCareFixture();for(const scope of ['rs-igd-flow','rs-critical-care','rs-nurse-station','rs-maternity']){await policy('authority',scope,{rules:['episode.open','episode.accept','episode.transfer','episode.close','episode.attach','episode.link_birth','record','sign'].map(action=>({action:action==='episode.open'?action:'clinical.'+action,roles:action==='episode.open'?['super_admin','dokter','nurse']:['dokter','nurse'],separate_verifier:false}))});await policy('clinical_template',scope,{title:'Synthetic unit form',signer_roles:['dokter'],fields:[{key:'transfer_target',label:'Destination',type:'text',required:false},{key:'exit_kind',label:'Exit',type:'text',required:false},{key:'child_admission_id',label:'Child',type:'number',required:false},{key:'birth_identity_verified',label:'Identity',type:'boolean',required:false},{key:'observation',label:'Observation',type:'number',required:false}]});}let ep,baby;
await check('explicit cutover, ownership, duplicate current episode and retry',async()=>{await actor();await assert.rejects(()=>cmd('open',{admission_id:1,unit:'rs-igd-flow',physical_unit_id:1}),/Cutover/);await assert.rejects(()=>cmd('open',{admission_id:3,unit:'rs-igd-flow',physical_unit_id:1,cutover_at:new Date().toISOString()}),/tenant/);await assert.rejects(()=>cmd('open',{admission_id:1,unit:'rs-igd-flow',physical_unit_id:3,cutover_at:new Date().toISOString()}),/Unit fisik/);const data={admission_id:1,unit:'rs-igd-flow',physical_unit_id:1,cutover_at:new Date().toISOString()},k=key();ep=await cmd('open',data,k);assert.deepEqual(await cmd('open',data,k),ep);await assert.rejects(()=>cmd('open',data),/unique/i);});
await check('professional recipient, separate handover receiver and stale version',async()=>{await actor();await assert.rejects(()=>step(ep,'accept'),/Peran|Kewenangan/);await actor(f.worker,f.A,'dokter');ep=await step(ep,'accept');assert.equal(ep.state,'active');await assert.rejects(()=>step({...ep,version:1},'attach',{clinical_record_id:999,observed_at:new Date().toISOString()}),/berubah/);});
await check('observations require signed source with matching scope and episode time',async()=>{const c=await clinical('rs-igd-flow',1,{observation:123});await step(ep,'attach',{clinical_record_id:c.id,observed_at:new Date().toISOString()});await assert.rejects(()=>step(ep,'attach',{clinical_record_id:c.id,observed_at:new Date(Date.now()+60000).toISOString()}),/Waktu/);assert.equal((await q('SELECT count(*)::int n FROM rs_episode_clinical_links'))[0].n,1);});
await check('unit transfer is atomic and references professional decision without a new encounter',async()=>{const c=await clinical('rs-igd-flow',1,{transfer_target:'rs-critical-care'});await assert.rejects(()=>step(ep,'transfer',{unit:'rs-nurse-station',physical_unit_id:1,clinical_record_id:c.id}),/Tujuan/);const tr=await step(ep,'transfer',{unit:'rs-critical-care',physical_unit_id:1,clinical_record_id:c.id});ep=tr.to;assert.equal(tr.from.state,'transferred');assert.equal(ep.admission_id,1);await assert.rejects(()=>step(ep,'accept'),/berbeda/);await actor(f.receiver,f.A,'dokter');ep=await step(ep,'accept');assert.equal((await q('SELECT count(*)::int n FROM rs_encounter_lifecycle'))[0].n,1);});
await check('mother and newborn link retains separate encounters and independent exit',async()=>{await q("INSERT INTO admissions(tenant_id,patient_name,mr_number,visit_number) VALUES($1,'Synthetic newborn','SYN-BABY','SYN-BIRTH')",[f.A]);const c=await clinical('rs-maternity',1,{child_admission_id:4,birth_identity_verified:true});const link=await cmd('link_birth',{mother_admission_id:1,child_admission_id:4,clinical_record_id:c.id});assert.equal(link.child_admission_id,4);await actor();baby=await cmd('open',{admission_id:4,unit:'rs-maternity',physical_unit_id:1,cutover_at:new Date().toISOString()});await actor(f.worker,f.A,'dokter');baby=await step(baby,'accept');await assert.rejects(()=>cmd('link_birth',{mother_admission_id:1,child_admission_id:3,clinical_record_id:c.id}),/Catatan/);});
await check('exit requires current decision and completion of pending work; closed visit cannot reopen',async()=>{const c=await clinical('rs-critical-care',1,{exit_kind:'discharge'});await actor();const order=await rpc('rs_create_order',['rs-nurse-station','Synthetic pending task','Synthetic unit',1,'normal',key()]);await actor(f.worker,f.A,'dokter');await assert.rejects(()=>step(ep,'close',{exit_kind:'discharge',clinical_record_id:c.id}),/Tugas aktif/);await actor();await rpc('rs_transition_order',[order.id,order.version,'cancel',JSON.stringify({reason:'Synthetic not needed'}),key()]);await actor(f.worker,f.A,'dokter');ep=await step(ep,'close',{exit_kind:'discharge',clinical_record_id:c.id});assert.equal(ep.state,'completed');assert.equal((await q('SELECT state FROM rs_care_episodes WHERE id=$1',[baby.id]))[0].state,'active');await actor();await assert.rejects(()=>cmd('open',{admission_id:1,unit:'rs-igd-flow',physical_unit_id:1,cutover_at:new Date().toISOString()}),/tertutup/);});
await check('tenant, viewer and direct mutation denied',async()=>{await actor(f.foreign,f.B);await assert.rejects(()=>step(baby,'close',{exit_kind:'discharge',clinical_record_id:999}),/tidak ditemukan/);await actor(f.worker,f.A,'viewer');await assert.rejects(()=>cmd('open',{admission_id:2,unit:'rs-igd-flow',physical_unit_id:1,cutover_at:new Date().toISOString()}),/Peran/);await actor();await pg.exec('SET ROLE authenticated');await assert.rejects(()=>q('DELETE FROM rs_care_episodes'),/permission denied/);await q("SELECT set_config('app.tenant_id',$1,false)",[f.B]);assert.equal((await q('SELECT count(*)::int n FROM rs_care_episodes'))[0].n,0);await pg.exec('RESET ROLE');});
}catch(e){error=e;}finally{if(pg){await pg.close();closed=true;}const out=path.join(__dirname,'../../docs/audit-evidence/2026-10-09');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'care-episode-simulation.json'),JSON.stringify({synthetic:true,cleanup:{database_closed:closed,live_records_created:0},results,error:error?.message},null,2)+'\n');}if(error)throw error;})().catch(e=>{console.error(e);process.exitCode=1;});
