// OWNED_BY: generic. Actual PostgreSQL RPC/trigger simulation; synthetic fixtures only.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/audit-evidence/2026-10-06');
const types=JSON.parse(fs.readFileSync(path.join(root,'config/rs-workflows.json'),'utf8'));
const A='10000000-0000-0000-0000-000000000001',B='10000000-0000-0000-0000-000000000002';
const admin='20000000-0000-0000-0000-000000000001',receiver='20000000-0000-0000-0000-000000000002',worker='20000000-0000-0000-0000-000000000003',foreign='20000000-0000-0000-0000-000000000004';
let pg,steps=[],seq=0;const roleActors={};
async function check(name,fn){await fn();steps.push({name,status:'passed'});console.log('PASS '+name);}
async function query(sql,args=[]){return (await pg.query(sql,args)).rows;}
async function rpc(name,args){const p=args.map((_,i)=>'$'+(i+1)).join(',');return (await query(`SELECT public.${name}(${p}) AS result`,args))[0].result;}
async function actor(id=admin,tenant=A,role='super_admin'){await pg.query('UPDATE user_profiles SET role=$1 WHERE id=$2',[role,id]);await query("SELECT set_config('app.user_id',$1,false),set_config('app.tenant_id',$2,false)",[id,tenant]);}
async function reject(fn,pattern){await assert.rejects(fn,pattern);}
function key(){return 'synthetic-'+(++seq);}
async function order(kind,admission=1){return rpc('rs_create_order',[kind,'Synthetic workflow','Ward synthetic',admission,'normal',key()]);}
async function assign(r,id=admin){return rpc('rs_transition_order',[r.id,r.version,'assign',JSON.stringify({assignee_id:id}),key()]);}
async function advance(r,evidence,k=key()){return rpc('rs_transition_order',[r.id,r.version,'advance',JSON.stringify(evidence),k]);}
(async()=>{
 pg=await require('../lib/hospital-fixture.cjs').createHospitalFixture();
 await check('migrations can be reapplied',async()=>{for(const name of ['0070_hospital_operations.sql','0071_hospital_bed_flow.sql','0072_hospital_staff_roles.sql','0073_hospital_operations_hardening.sql'])await pg.exec(fs.readFileSync(path.join(root,'db/migrations',name),'utf8'));assert.equal((await query('SELECT count(*)::int AS n FROM rs_workflow_types'))[0].n,18);});
 // Map synthetic ownership during setup before guards; production mapping uses reviewed runbook.
 await pg.exec(`INSERT INTO inpatient_beds(tenant_id,ward_id,room_no,bed_no,class_code,status,is_active) VALUES('${A}',1,'SYN-ROOM','SYN-BED','1','Kosong',true),('${B}',2,'SYN-B','SYN-B','1','Kosong',true);`);
 await check('anonymous and viewer mutations denied',async()=>{await actor(worker,A,'viewer');await reject(()=>order('rs-transport'),/Peran/);await query("SELECT set_config('app.user_id','',false)");await reject(()=>order('rs-transport'),/Login/);await actor(worker,A,'housekeeping');await actor();});
 await check('foreign admission rejected',async()=>{await reject(()=>order('rs-transport',3),/tenant/);});
 await check('creation replay and conflicting replay',async()=>{const k=key();const args=['rs-transport','Synthetic request','Ward synthetic',1,'normal',k];const r=await rpc('rs_create_order',args);assert.equal((await rpc('rs_create_order',args)).id,r.id);await reject(()=>rpc('rs_create_order',[...args.slice(0,1),'Different title',...args.slice(2)]),/input berbeda/);});
 await check('assignment, stage evidence, stale version and role enforcement',async()=>{let r=await order('rs-transport');await reject(()=>advance(r,{}),/Tugaskan/);r=await assign(r);await actor(admin,A,'porter');await reject(()=>advance(r,{}),/wajib/);await reject(()=>rpc('rs_transition_order',[r.id,1,'advance','{}',key()]),/Data berubah/);await actor(receiver,A,'nurse');await reject(()=>advance(r,{asal:'ward',tujuan:'radiology',petugas_kendaraan:'porter'}),/peran/);await actor();});
 await check('all 18 operational workflows complete actual SQL stages',async()=>{
  for(const role of new Set(types.flatMap(t=>[...t.owner_roles,...t.stages.flatMap(s=>s.roles)]))){const id='30000000-0000-0000-0000-'+String(Object.keys(roleActors).length+1).padStart(12,'0');roleActors[role]=id;await pg.query('INSERT INTO user_profiles(id,tenant_id,role,full_name) VALUES($1,$2,$3,$4)',[id,A,role,'Synthetic '+role]);}
  for(const t of types){const owner=roleActors[t.owner_roles[0]];await actor(owner,A,t.owner_roles[0]);let r=await order(t.code,t.patient_required?1:null);r=await assign(r,owner);for(const stage of t.stages){await actor(stage.receiver?receiver:roleActors[stage.roles[0]],A,stage.receiver?'nurse':stage.roles[0]);const evidence=Object.fromEntries(stage.fields.map(f=>[f,'Synthetic evidence: '+f]));r=await advance(r,evidence);}assert.equal(r.status,'completed',t.code);assert.equal(r.stage,t.stages.length);}
  await actor();
 });
 await check('handover requires another receiver',async()=>{let r=await assign(await order('rs-nurse-station'));await actor(admin,A,'nurse');for(const s of types.find(t=>t.code===r.kind).stages.slice(0,2))r=await advance(r,Object.fromEntries(s.fields.map(f=>[f,'Synthetic evidence'])));await reject(()=>advance(r,{konfirmasi_penerimaan:'Synthetic accepted',rencana_tindak_lanjut:'Synthetic followup'}),/berbeda/);await actor();});
 await check('completed and cancelled records cannot advance',async()=>{let r=await order('rs-linen',null);r=await rpc('rs_transition_order',[r.id,r.version,'cancel',JSON.stringify({reason:'Synthetic cancel'}),key()]);await reject(()=>assign(r),/ditutup/);});
 await check('transition retry is idempotent and mismatched evidence rejected',async()=>{let r=await assign(await order('rs-transport'));const evidence={asal:'Synthetic ward',tujuan:'Synthetic radiology',petugas_kendaraan:'Synthetic porter'},k=key();await actor(admin,A,'porter');const done=await advance(r,evidence,k);assert.equal((await advance(r,evidence,k)).version,done.version);await reject(()=>advance(r,{...evidence,asal:'changed'},k),/aksi berbeda/);await actor();});
 let request,stay;
 await check('bed request replay, foreign bed and competing allocation',async()=>{const k=key();request=await rpc('rs_request_bed',[1,'Synthetic requirements',k]);assert.equal((await rpc('rs_request_bed',[1,'Synthetic requirements',k])).id,request.id);await reject(()=>rpc('rs_allocate_bed',[request.id,2,4]),/tidak tersedia/);request=await rpc('rs_allocate_bed',[request.id,1,4]);const other=await rpc('rs_request_bed',[2,'Synthetic waiting',key()]);await reject(()=>rpc('rs_allocate_bed',[other.id,1,4]),/unique|duplicate/i);await reject(()=>rpc('inp_admit_patient',[2,1,null,'Synthetic doctor','Synthetic diagnosis',null,'IGD','Umum',null]),/pasien lain/);});
 await check('reserved patient admitted by real existing inpatient RPC',async()=>{stay=await rpc('inp_admit_patient',[1,1,null,'Synthetic doctor','Synthetic diagnosis',null,'IGD','Umum',null]);assert.equal(stay.ok,true);assert.equal((await query('SELECT status FROM rs_bed_reservations WHERE id=$1',[request.id]))[0].status,'admitted');assert.equal((await query('SELECT tenant_id FROM inpatient_stays WHERE id=$1',[stay.stay_id]))[0].tenant_id,A);});
 await check('discharge blocked without current episode checklist',async()=>{await actor(admin,A,'dokter');await reject(()=>rpc('inp_discharge_patient',[stay.stay_id,'Pulang','Synthetic diagnosis',null,null,null,null,null,null,'Membaik',null,null]),/Checklist/);await actor();});
 await check('discharge checklist then real discharge creates housekeeping',async()=>{let r=await assign(await order('rs-discharge'));for(const stage of types.find(t=>t.code===r.kind).stages){await actor(admin,A,stage.roles[0]);r=await advance(r,Object.fromEntries(stage.fields.map(f=>[f,'Synthetic source evidence'])));}await actor(admin,A,'dokter');const result=await rpc('inp_discharge_patient',[stay.stay_id,'Pulang','Synthetic diagnosis',null,null,null,'Synthetic summary','Synthetic medication','Synthetic instructions','Membaik',null,null]);assert.equal(result.ok,true);assert.equal((await query('SELECT status FROM inpatient_beds WHERE id=1'))[0].status,'Dibersihkan');assert.ok((await query("SELECT id FROM rs_work_orders WHERE kind='rs-housekeeping' AND details->>'bed_id'='1'"))[0]);await actor();});
 await check('manual clean release denied; housekeeping verifies and releases bed',async()=>{await reject(()=>rpc('inp_set_bed_status',[1,'Kosong',null]),/Housekeeping/);let r=(await query("SELECT * FROM rs_work_orders WHERE kind='rs-housekeeping' AND details->>'bed_id'='1'"))[0];r=await assign(r,worker);await actor(worker,A,'housekeeping');for(const s of types.find(t=>t.code===r.kind).stages.slice(0,2))r=await advance(r,Object.fromEntries(s.fields.map(f=>[f,'Synthetic cleaning evidence'])));await reject(()=>advance(r,{verifikasi_kamar:'Synthetic clean',petugas_verifikasi:'Synthetic supervisor'}),/peran/);await actor(admin,A,'admin');r=await advance(r,{verifikasi_kamar:'Synthetic clean',petugas_verifikasi:'Synthetic supervisor'});assert.equal(r.status,'completed');assert.equal((await query('SELECT status FROM inpatient_beds WHERE id=1'))[0].status,'Kosong');const waiting=(await query("SELECT id FROM rs_bed_reservations WHERE admission_id=2 AND status='waiting'"))[0];assert.equal((await rpc('rs_allocate_bed',[waiting.id,1,4])).status,'reserved');await actor();});
 await check('cross tenant mutation, staff directory and RLS reads',async()=>{const r=await order('rs-transport');await actor(foreign,B);await reject(()=>assign(r),/tenant/);assert.equal((await query('SELECT * FROM rs_staff_directory()')).length,1);await actor();await pg.exec('GRANT USAGE ON SCHEMA public,auth TO authenticated;');await pg.exec('SET ROLE authenticated;');assert.equal((await query("SELECT count(*)::int AS n FROM rs_work_orders WHERE tenant_id=$1",[B]))[0].n,0);await reject(()=>query("UPDATE rs_work_orders SET title='Unauthorized'"),/permission denied/);await pg.exec('RESET ROLE;');});
 await check('administrator cannot substitute clinical stage profession',async()=>{let r=await assign(await order('rs-discharge'));await reject(()=>advance(r,{referensi_resume:'Synthetic resume',instruksi_kontrol:'Synthetic followup',persetujuan_dpjp:'Synthetic doctor'}),/profesi/);});
 await check('hospital role provisioning and unauthorized role changes',async()=>{const result=await rpc('set_user_access',[worker,'housekeeping',['rs-housekeeping','rs-linen']]);assert.equal(result.ok,true);await actor(worker,A,'housekeeping');await reject(()=>rpc('set_user_access',[receiver,'dokter',['rs-discharge']]),/Super Admin/);await actor();await reject(()=>rpc('set_user_access',[foreign,'nurse',['rs-nurse-station']]),/tenant berbeda/);});
 await check('role-specific reads and viewer data exclusion',async()=>{await actor(worker,A,'housekeeping');await pg.exec('SET ROLE authenticated;');const rows=await query('SELECT kind FROM rs_work_orders');assert.ok(rows.length>0);assert.ok(rows.every(r=>['rs-housekeeping','rs-linen'].includes(r.kind)));await pg.exec('RESET ROLE;');await actor(worker,A,'viewer');await pg.exec('SET ROLE authenticated;');assert.equal((await query('SELECT count(*)::int AS n FROM rs_work_orders'))[0].n,0);assert.equal((await query('SELECT count(*)::int AS n FROM rs_work_events'))[0].n,0);await pg.exec('RESET ROLE;');await actor();});
 await check('expiry and cancellation release reservation without occupying bed',async()=>{await pg.query('INSERT INTO admissions(tenant_id,patient_name) VALUES($1,$2),($1,$3)',[A,'Synthetic expiry patient','Synthetic next patient']);const b=(await query("INSERT INTO inpatient_beds(tenant_id,ward_id,room_no,bed_no,status,is_active) VALUES($1,1,'SYN-EXP','SYN-EXP','Kosong',true) RETURNING id",[A]))[0];const r=await rpc('rs_request_bed',[4,'Synthetic requirements',key()]);await rpc('rs_allocate_bed',[r.id,b.id,1]);await query("UPDATE rs_bed_reservations SET expires_at=now()-interval '1 minute' WHERE id=$1",[r.id]);const waiting=await rpc('rs_request_bed',[5,'Synthetic next requirements',key()]);await rpc('rs_allocate_bed',[waiting.id,b.id,1]);assert.equal((await query('SELECT status FROM rs_bed_reservations WHERE id=$1',[r.id]))[0].status,'expired');await rpc('rs_cancel_bed',[waiting.id,'Synthetic cancel']);assert.equal((await rpc('rs_bed_capacity',[])).available,1);assert.ok((await query('SELECT count(*)::int AS n FROM rs_bed_events'))[0].n>=8);});
 await check('authenticated bed reads, master RPC and direct write rejection',async()=>{await actor();await pg.exec('SET ROLE authenticated;');const beds=await query('SELECT id,tenant_id FROM inpatient_beds');assert.equal(beds.length,2);assert.ok(beds.every(b=>b.tenant_id===A));await reject(()=>query("UPDATE inpatient_beds SET status='Kosong' WHERE id=1"),/permission denied/);await pg.exec('RESET ROLE;');const rows=await rpc('rs_save_beds',[null,JSON.stringify([{ward_id:1,class_code:'1',room_no:'SYN-MASTER',bed_no:'SYN-MASTER',notes:'Synthetic only'}])]);assert.equal(rows.length,1);assert.equal(rows[0].tenant_id,A);await actor(receiver,A,'nurse');await reject(()=>rpc('rs_save_beds',[rows[0].id,JSON.stringify([{ward_id:1,class_code:'1',room_no:'SYN-MASTER',bed_no:'SYN-MASTER'}])]),/peran/);await actor();});
 await check('audit events persisted for completed flow',async()=>{const n=(await query('SELECT count(*)::int AS n FROM rs_work_events'))[0].n;assert.ok(n>90);});
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'hospital-operations-simulation.json'),JSON.stringify({synthetic:true,engine:'PGlite/PostgreSQL actual migrations and existing inpatient RPCs',limitations:['post_journal and write_audit sinks use synthetic fixture tables; not accounting or production UAT','simulated competing allocations run sequentially; unique constraints and row locks verified, multi-session PostgreSQL concurrency still requires staging'],steps},null,2));
 await pg.close();console.log(`${steps.length} scenarios passed`);
})().catch(async e=>{console.error(e);if(pg)await pg.close();process.exitCode=1;});
