// OWNED_BY: generic. Approved synthetic calculation cases, no charge/payment mutation.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),f=require('../lib/workforce-fixture.cjs');let pg,failure,closed=false;const results=[],start='2026-10-08T00:00:00Z';
const policy={room_method:'24_hour',transfer_method:'prorata',timezone:'UTC',cutoff:'00:00',rounding:'up',minimum_units:0,amount_decimals:2,rounding_rate_basis:'weighted_period_average'};
async function quote(end,segments,p={}){return(await pg.query('SELECT rs_room_billing_quote($1,$2,$3,$4) r',[JSON.stringify({...policy,...p}),start,end,JSON.stringify(segments)])).rows[0].r;}
const segment=(s,e,rate=100,code='SYN-CLASS')=>({starts_at:s,ends_at:e,rate,class_code:code});async function check(name,fn){await fn();results.push({name,status:'passed'});console.log('PASS '+name);}
(async()=>{try{pg=await f.createWorkforceFixture();await pg.exec(fs.readFileSync(path.join(__dirname,'../../db/migrations/0082_room_billing_calculator.sql'),'utf8'));
await check('24h prorata class transfer preserves weighted tariff',async()=>{const end='2026-10-09T00:00:00Z',mid='2026-10-08T12:00:00Z',r=await quote(end,[segment(start,mid,100),segment(mid,end,200)]);assert.equal(r.total,150);assert.equal(r.billed_units,1);assert.equal(r.lines.length,1);});
await check('highest and cutoff use distinct approved rules',async()=>{const end='2026-10-09T00:00:00Z',mid='2026-10-08T12:00:00Z',s=[segment(start,mid,100),segment(mid,end,200)];assert.equal((await quote(end,s,{transfer_method:'highest'})).total,200);assert.equal((await quote(end,s,{transfer_method:'cutoff',opening_cutoff_rate:100,cutoff_rate_reference:'latest_daily_at_period_start'})).total,100);});
await check('hourly rounding and minimum are explicit and line sums equal total',async()=>{const end='2026-10-08T01:30:00Z',s=[segment(start,end,100)];for(const [rounding,total,units] of [['up',200,2],['nearest',200,2],['down',100,1]]){const r=await quote(end,s,{room_method:'hourly',rounding});assert.equal(r.total,total);assert.equal(r.billed_units,units);assert.equal(r.lines.reduce((a,l)=>a+l.amount,0),total);}assert.equal((await quote(end,s,{room_method:'hourly',minimum_units:3})).total,300);});
await check('calendar cutoff uses half-open occupied periods without midnight extra day',async()=>{const end='2026-10-09T00:00:00Z',s=[segment(start,end)];assert.equal((await quote(end,s,{room_method:'calendar'})).total,100);assert.equal((await quote('2026-10-09T00:00:01Z',[segment(start,'2026-10-09T00:00:01Z')],{room_method:'calendar'})).total,200);});
await check('local calendar DST is based on local day rather than fixed 24 hours',async()=>{const begin='2026-03-08T05:00:00Z',end='2026-03-09T04:00:00Z';const r=(await pg.query('SELECT rs_room_billing_quote($1,$2,$3,$4) r',[JSON.stringify({...policy,room_method:'calendar',timezone:'America/New_York'}),begin,end,JSON.stringify([segment(begin,end)])])).rows[0].r;assert.equal(r.total,100);assert.equal(r.lines.length,1);});
await check('gaps, overlap, negative rates and incomplete policy are rejected',async()=>{const end='2026-10-09T00:00:00Z',mid='2026-10-08T12:00:00Z';await assert.rejects(()=>quote(end,[segment(mid,end)]),/Segmen/);await assert.rejects(()=>quote(end,[segment(start,mid),segment(start,end)]),/Segmen/);await assert.rejects(()=>quote(end,[segment(start,end,-1)]),/Segmen/);await assert.rejects(()=>quote(end,[segment(start,end)],{amount_decimals:null}),/presisi/);await assert.rejects(()=>quote(end,[segment(start,end)],{transfer_method:'cutoff'}),/opening/);});
await check('constant tariff is invariant under source segmentation and cutoff reference is explicit',async()=>{const end='2026-10-09T00:00:00Z',mid='2026-10-08T12:00:00Z';for(const room_method of ['calendar','24_hour','hourly'])for(const transfer_method of ['prorata','highest']){const p={room_method,transfer_method};assert.deepEqual(await quote(end,[segment(start,end,123.45)],p),await quote(end,[segment(start,mid,123.45),segment(mid,end,123.45)],p));}await assert.rejects(()=>quote(end,[segment(start,end)],{transfer_method:'cutoff',opening_cutoff_rate:100}),/Referensi cutoff/);});
await check('no charge source mutation and no authenticated calculator exposure',async()=>{assert.equal((await pg.query('SELECT count(*)::int n FROM inpatient_charges')).rows[0].n,0);await pg.exec('SET ROLE authenticated');await assert.rejects(()=>quote('2026-10-09T00:00:00Z',[segment(start,'2026-10-09T00:00:00Z')]),/permission denied/);await pg.exec('RESET ROLE');});
}catch(e){failure=e;}finally{if(pg){await pg.close();closed=true;}const out=path.join(__dirname,'../../docs/audit-evidence/2026-10-09');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'room-billing-calculator.json'),JSON.stringify({synthetic:true,calculator_only:true,source_posting_complete:false,cleanup:{database_closed:closed,live_records_created:0},results,error:failure?.message},null,2)+'\n');}if(failure)throw failure;})().catch(e=>{console.error(e);process.exitCode=1;});
