// OWNED_BY: generic. Real migrations and synthetic in-memory source data.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),f=require('../lib/rs-engine-fixture.cjs');let pg,n=0,error,closed=false;const results=[],key=()=>`synthetic-tech-${++n}`;
async function q(sql,args=[]){return(await pg.query(sql,args)).rows;}
async function actor(id=f.admin,tenant=f.A,role='super_admin'){await q('UPDATE user_profiles SET role=$1 WHERE id=$2',[role,id]);await q("SELECT set_config('app.user_id',$1,false),set_config('app.tenant_id',$2,false)",[id,tenant]);}
async function cmd(kind,action,data,k=key()){return(await q('SELECT tech_ops_command($1,$2,$3,$4) r',[kind,action,JSON.stringify({reason:'Synthetic evidence',...data}),k]))[0].r;}
async function next(kind,row,action,data={}){return cmd(kind,action,{id:row.id,version:row.ops_version,...data});}
async function check(name,fn){await fn();results.push({name,status:'passed'});console.log('PASS '+name);}
(async()=>{try{pg=await f.createEngineFixture();for(const file of ['0065_tech_operations_control_plane.sql','0079_tech_operational_lifecycle.sql'])await pg.exec(fs.readFileSync(path.join(__dirname,'../../db/migrations',file),'utf8'));let ticket,change,deployment;
await check('ticket create retry and changed input rejected',async()=>{const k=key(),data={title:'Synthetic issue',description:'Synthetic problem',priority:'P1'};ticket=await cmd('ticket','create',data,k);assert.deepEqual(await cmd('ticket','create',data,k),ticket);await assert.rejects(()=>cmd('ticket','create',{...data,priority:'P0'},k),/Retry/);await assert.rejects(()=>next('ticket',ticket,'resolve',{resolution:'Not started'}),/Transisi/);});
await check('triage, assignment, waiting, resolution and independent close',async()=>{await assert.rejects(()=>next('ticket',ticket,'triage'),/pemilik/);await q('UPDATE user_profiles SET role=$1 WHERE id=$2',['tech',f.worker]);ticket=await next('ticket',ticket,'triage',{owner:f.worker});await actor(f.worker,f.A,'tech');ticket=await next('ticket',ticket,'start');ticket=await next('ticket',ticket,'wait');ticket=await next('ticket',ticket,'start');await assert.rejects(()=>next('ticket',ticket,'resolve'),/Bukti/);ticket=await next('ticket',ticket,'resolve',{resolution:'Synthetic fixed and verified'});await assert.rejects(()=>next('ticket',ticket,'close'),/berbeda/);await actor();ticket=await next('ticket',ticket,'close');assert.equal(ticket.status,'CLOSED');ticket=await next('ticket',ticket,'reopen');assert.equal(ticket.status,'TRIAGED');});
await check('release maker-checker, preflight/result and stale version enforced',async()=>{change=await cmd('change','create',{title:'Synthetic release',type:'code',risk:'Synthetic risk assessment',rollback:'Synthetic rollback procedure'});change=await next('change',change,'submit');await assert.rejects(()=>next('change',change,'approve'),/berbeda/);await actor(f.receiver,f.A,'direktur');change=await next('change',change,'approve');await assert.rejects(()=>next('change',change,'start'),/preflight/);await actor();change=await next('change',change,'start',{preflight:{reference:'Synthetic local test evidence'}});await assert.rejects(()=>next('change',{...change,ops_version:1},'complete',{release:'1.0',result:{reference:'Synthetic'}}),/berubah/);change=await next('change',change,'complete',{release:'1.0',result:{reference:'Synthetic completed tests'}});});
await check('deployment requires succeeded source, same version and independent verifier',async()=>{await assert.rejects(()=>cmd('deployment','report',{change_id:change.id,release:'2.0',module:'his',installation:'SYN-CLIENT',environment:'test',evidence:'Synthetic local install'}),/versi/);deployment=await cmd('deployment','report',{change_id:change.id,release:'1.0',module:'his',installation:'SYN-CLIENT',environment:'test',evidence:'Synthetic local install'});await assert.rejects(()=>next('deployment',deployment,'verify',{evidence:'Self verification'}),/berbeda/);await actor(f.receiver,f.A,'direktur');deployment=await next('deployment',deployment,'verify',{evidence:'Synthetic independent observation'});assert.equal(deployment.state,'verified');await actor();});
await check('rollback revokes deployment; source history survives',async()=>{change=await next('change',change,'rollback',{result:{reference:'Synthetic rollback verified'}});assert.equal((await q('SELECT state FROM tech_module_deployments WHERE id=$1',[deployment.id]))[0].state,'revoked');assert.ok((await q('SELECT count(*)::int n FROM tech_ops_history'))[0].n>10);await assert.rejects(()=>cmd('deployment','report',{change_id:change.id,release:'1.0',module:'his',installation:'SYN-CLIENT',environment:'test',evidence:'Synthetic local install'}),/sukses/);});
await check('tenant and role isolation, pagination and direct writes denied',async()=>{await actor(f.foreign,f.B);await assert.rejects(()=>next('ticket',ticket,'start'),/tidak ditemukan/);assert.equal((await q("SELECT tech_ops_board('ticket',0) r"))[0].r.rows.length,0);await actor(f.worker,f.A,'viewer');await assert.rejects(()=>cmd('ticket','create',{title:'Synthetic',description:'Synthetic',priority:'P1'}),/Peran/);await actor();await assert.rejects(()=>q("SELECT tech_ops_board('ticket',-1)"),/Offset/);await pg.exec('SET ROLE authenticated');await assert.rejects(()=>q("UPDATE tech_support_tickets SET status='CLOSED'"),/permission denied/);await assert.rejects(()=>q('DELETE FROM tech_ops_history'),/permission denied/);await pg.exec('RESET ROLE');});
}catch(e){error=e;}finally{if(pg){await pg.close();closed=true;}const out=path.join(__dirname,'../../docs/audit-evidence/2026-10-09');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'tech-lifecycle-simulation.json'),JSON.stringify({synthetic:true,cleanup:{database_closed:closed,live_records_created:0},results,error:error?.message},null,2)+'\n');}if(error)throw error;})().catch(e=>{console.error(e);process.exitCode=1;});
