// OWNED_BY: generic. Synthetic in-memory source contracts; no production writes.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),f=require('../lib/rs-engine-fixture.cjs');
let pg,n=0,results=[],failure,closed=false;const key=()=>`synthetic-stock-${++n}`;
async function q(sql,args=[]){return(await pg.query(sql,args)).rows;}
async function rpc(name,args){return(await q(`SELECT ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args))[0].result;}
async function actor(id=f.admin,tenant=f.A,role='super_admin'){await q('UPDATE user_profiles SET role=$1 WHERE id=$2',[role,id]);await q("SELECT set_config('app.user_id',$1,false),set_config('app.tenant_id',$2,false)",[id,tenant]);}
async function activate(kind,payload){await actor();let p=await rpc('ops_policy_command',[null,'create',JSON.stringify({kind,scope:kind==='stock_opening'?'stock-lot:1':'rs-linen',payload,reason:'Synthetic policy'}),key()]);p=await rpc('ops_policy_command',[p.id,'submit',JSON.stringify({expected_state:'draft',reason:'Synthetic submit'}),key()]);await actor(f.receiver,f.A,'direktur');p=await rpc('ops_policy_command',[p.id,'approve',JSON.stringify({expected_state:'in_review',reason:'Synthetic approve'}),key()]);await rpc('ops_policy_command',[p.id,'activate',JSON.stringify({expected_state:'approved',reason:'Synthetic activate',effective_at:new Date().toISOString()}),key()]);await actor();}
const command=(action,data={},k=key())=>rpc('rs_stock_command',[action,JSON.stringify({batch_id:1,scope:'rs-linen',warehouse_id:1,state:'available',reason:'Synthetic stock operation',...data}),k]);
async function check(name,fn){await fn();results.push({name,status:'passed'});console.log('PASS '+name);}
async function balance(expected){const r=(await q('SELECT stock_qty FROM inventory_items WHERE id=1'))[0];assert.equal(Number(r.stock_qty),expected);assert.equal(Number((await q('SELECT qty_remaining FROM inventory_batches WHERE id=1'))[0].qty_remaining),expected);assert.equal(Number((await q('SELECT sum(qty) qty FROM rs_lot_positions WHERE batch_id=1'))[0].qty),expected);}
(async()=>{try{
 pg=await f.createEngineFixture();await activate('authority',{rules:['initialize','reconcile','receive','issue','return','transfer','quarantine','release','waste','link_order'].map(a=>({action:'stock.'+a,roles:['super_admin'],separate_verifier:a==='release'}))});
 await activate('stock_opening',{batch_id:1,domain:'linen',timezone:'Asia/Jakarta',positions:[{warehouse_id:1,state:'available',qty:0}]});
 await check('approved opening required and tenant ownership enforced',async()=>{await assert.rejects(()=>command('receive',{qty:10}),/opening/);await command('initialize');await assert.rejects(()=>command('initialize'),/sudah/);await assert.rejects(()=>command('receive',{batch_id:2,qty:10}),/tenant/);});
 await check('receive synchronizes batch, master, location and source ledger once',async()=>{const k=key(),data={qty:10};const r=await command('receive',data,k);assert.deepEqual(await command('receive',data,k),r);await assert.rejects(()=>command('receive',{qty:11},k),/Retry/);await balance(10);});
 let issued;
 await check('transfer preserves total; issue and referenced return preserve traceability',async()=>{await command('transfer',{qty:3,destination_id:2});await balance(10);issued=await command('issue',{qty:2,admission_id:1});await balance(8);await command('return',{qty:1,return_of:issued.ledger_id,admission_id:1});await balance(9);await assert.rejects(()=>command('return',{qty:2,return_of:issued.ledger_id,admission_id:1}),/melebihi/);await assert.rejects(()=>command('return',{qty:1,return_of:issued.ledger_id,admission_id:2}),/sumber/);});
 await check('quarantine blocks issue and requires separate release verifier',async()=>{await command('quarantine',{qty:5});await assert.rejects(()=>command('issue',{qty:2}),/cukup/);await assert.rejects(()=>command('release',{qty:1}),/berbeda|sendiri|verifier|pemisahan/i);await actor(f.receiver,f.A,'super_admin');await command('release',{qty:2});await command('quarantine',{qty:1});await actor();await assert.rejects(()=>command('release',{qty:1}),/berbeda|sendiri|verifier|pemisahan/i);await command('waste',{qty:1,state:'quarantine'});await balance(8);});
 await check('invalid quantities, expiry, destinations and foreign admissions roll back',async()=>{for(const qty of [0,-1,'2'])await assert.rejects(()=>command('receive',{qty}),/Kuantitas/);await assert.rejects(()=>command('transfer',{qty:1,destination_id:3}),/tujuan/);await assert.rejects(()=>command('issue',{qty:1,admission_id:3}),/tenant/);await q('UPDATE inventory_batches SET expiry_date=current_date-1 WHERE id=1');await assert.rejects(()=>command('issue',{qty:1}),/kedaluwarsa/);await q('UPDATE inventory_batches SET expiry_date=current_date+365 WHERE id=1');await balance(8);});
 await check('legacy source drift blocks use and approved reconciliation preserves history',async()=>{await q('UPDATE inventory_batches SET qty_remaining=7 WHERE id=1');await q('UPDATE inventory_items SET stock_qty=7 WHERE id=1');await q('UPDATE stock_by_location SET qty=qty-1 WHERE item_id=1 AND warehouse_id=1');await assert.rejects(()=>command('issue',{qty:1}),/rekonsiliasi/);await assert.rejects(()=>command('reconcile'),/versi baru/);await activate('stock_opening',{batch_id:1,domain:'linen',timezone:'Asia/Jakarta',positions:[{warehouse_id:1,state:'available',qty:2},{warehouse_id:1,state:'quarantine',qty:2},{warehouse_id:2,state:'available',qty:3}]});const before=(await q('SELECT count(*)::int n FROM stock_ledger'))[0].n;await command('reconcile');assert.equal((await q('SELECT count(*)::int n FROM stock_ledger'))[0].n,before+1);await balance(7);});
 await check('legacy ownership binds only approved existing source IDs without changing master keys',async()=>{await pg.exec("INSERT INTO inventory_items(item_code,item_name) VALUES('SYN-LEGACY','Synthetic legacy item');INSERT INTO warehouses(name) VALUES('Synthetic legacy warehouse')");await activate('stock_ownership',{sources:[{kind:'item',id:3},{kind:'warehouse',id:4}]});await rpc('rs_stock_bind_sources',['rs-linen']);assert.equal((await q("SELECT tenant_id FROM rs_inventory_source_owners WHERE source_kind='item' AND source_id=3"))[0].tenant_id,f.A);assert.equal((await q('SELECT tenant_id FROM inventory_items WHERE id=3'))[0].tenant_id,null);await actor(f.foreign,f.B);await assert.rejects(()=>rpc('ops_policy_command',[null,'create',JSON.stringify({kind:'stock_ownership',scope:'foreign-test',payload:{sources:[{kind:'item',id:3}]},reason:'Synthetic theft'}),key()]),/tenant lain/);await actor();});
 await check('viewer, direct mutation and cross-tenant reads denied',async()=>{await actor(f.worker,f.A,'viewer');await assert.rejects(()=>command('receive',{qty:1}),/Peran/);await actor();await pg.exec('GRANT SELECT,INSERT,UPDATE,DELETE ON stock_ledger TO authenticated; SET ROLE authenticated');await assert.rejects(()=>q('UPDATE stock_ledger SET qty=999 WHERE rs_operation IS NOT NULL'),/teraudit/);await assert.rejects(()=>q('DELETE FROM rs_lot_positions'),/permission denied/);await q("SELECT set_config('app.tenant_id',$1,false)",[f.B]);assert.equal((await q('SELECT count(*)::int n FROM rs_lot_positions'))[0].n,0);await pg.exec('RESET ROLE');});
}catch(e){failure=e;}finally{if(pg){await pg.close();closed=true;}const out=path.join(__dirname,'../../docs/audit-evidence/2026-10-09');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'shared-inventory-simulation.json'),JSON.stringify({synthetic:true,backend:'isolated in-memory PGlite',cleanup:{database_closed:closed,no_production_records_created:true},results,error:failure?.message},null,2)+'\n');}if(failure)throw failure;})().catch(e=>{console.error(e);process.exitCode=1;});
