// OWNED_BY: generic. Credential gate tests using actual SQL, no real staff data.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),f=require('../lib/workforce-fixture.cjs');let pg,error,closed=false,n=0;const results=[],key=()=>`synthetic-workforce-${++n}`,from=new Date(Date.now()-86400000).toISOString().slice(0,10),until=new Date(Date.now()+30*86400000).toISOString().slice(0,10);
async function q(s,a=[]){return(await pg.query(s,a)).rows;}async function rpc(name,a){return(await q(`SELECT ${name}(${a.map((_,i)=>'$'+(i+1)).join(',')}) r`,a))[0].r;}
async function actor(id=f.admin,t=f.A){await q("SELECT set_config('app.user_id',$1,false),set_config('app.tenant_id',$2,false)",[id,t]);}
const cmd=(entity,action,data,k=key())=>rpc('ops_workforce_command',[entity,action,JSON.stringify({reason:'Synthetic workforce evidence',...data}),k]);
async function approve(entity,row){row=await cmd(entity,'submit',{id:row.id,version:row.version});await actor(f.receiver);row=await cmd(entity,'approve',{id:row.id,version:row.version});await actor();return row;}
async function credential(user=f.worker){await actor();return approve('credential',await cmd('credential','create',{user_id:user,kind:'professional_authorization',reference:'SYN-CREDENTIAL',evidence:'Synthetic reviewer evidence',valid_from:from,valid_until:until}));}
async function check(name,fn){await fn();results.push({name,status:'passed'});console.log('PASS '+name);}
async function policy(kind,payload){await actor();let p=await rpc('ops_policy_command',[null,'create',JSON.stringify({kind,scope:'rs-igd-flow',payload,reason:'Synthetic configuration'}),key()]);p=await rpc('ops_policy_command',[p.id,'submit',JSON.stringify({expected_state:'draft',reason:'Synthetic review'}),key()]);await actor(f.worker);p=await rpc('ops_policy_command',[p.id,'approve',JSON.stringify({expected_state:'in_review',reason:'Synthetic professional review'}),key()]);await actor();return rpc('ops_policy_command',[p.id,'activate',JSON.stringify({expected_state:'approved',effective_at:new Date().toISOString(),reason:'Synthetic activate'}),key()]);}
(async()=>{try{pg=await f.createWorkforceFixture();let c,g,p,record;
await check('credential maker-checker, role, dates and retry',async()=>{const data={user_id:f.worker,kind:'STR',reference:'SYN-STR',evidence:'Synthetic credential',valid_from:from,valid_until:until},k=key();c=await cmd('credential','create',data,k);assert.deepEqual(await cmd('credential','create',data,k),c);await assert.rejects(()=>cmd('credential','create',{...data,reference:'Changed'},k),/Retry/);c=await cmd('credential','submit',{id:c.id,version:c.version});await assert.rejects(()=>cmd('credential','approve',{id:c.id,version:c.version}),/Peran/);await actor(f.worker);await assert.rejects(()=>cmd('credential','approve',{id:c.id,version:c.version}),/berbeda/);await actor(f.receiver);c=await cmd('credential','approve',{id:c.id,version:c.version});await actor();await assert.rejects(()=>cmd('credential','create',{...data,user_id:f.foreign}),/tenant/);await assert.rejects(()=>cmd('credential','create',{...data,valid_until:from,valid_from:until}),/Periode/);});
await check('explicit credential IDs and bounded grant period required',async()=>{const data={user_id:f.worker,scope:'rs-igd-flow',actions:['clinical.record','clinical.sign','clinical.template.review','clinical.authority.review'],credential_ids:[c.id],valid_from:from,valid_until:until,evidence:'Synthetic privileges'};await assert.rejects(()=>cmd('privilege','create',{...data,credential_ids:[]}),/eksplisit/);await assert.rejects(()=>cmd('privilege','create',{...data,actions:['admin.override']}),/tidak valid/);await assert.rejects(()=>cmd('privilege','create',{...data,valid_until:'2099-01-01'}),/periode/);g=await approve('privilege',await cmd('privilege','create',data));});
await check('named individual reviewer is required for clinical configuration activation',async()=>{const template={title:'Synthetic clinical form',signer_roles:['dokter'],fields:[{key:'observation',label:'Observation',type:'number',required:true}]};await actor();let pending=await rpc('ops_policy_command',[null,'create',JSON.stringify({kind:'clinical_template',scope:'rs-critical-care',payload:template,reason:'Synthetic draft'}),key()]);pending=await rpc('ops_policy_command',[pending.id,'submit',JSON.stringify({expected_state:'draft',reason:'Synthetic submit'}),key()]);await actor(f.receiver);await assert.rejects(()=>rpc('ops_policy_command',[pending.id,'approve',JSON.stringify({expected_state:'in_review',reason:'Synthetic reviewer without privilege'}),key()]),/Privilege/);await actor();await policy('authority',{rules:['record','sign'].map(a=>({action:'clinical.'+a,roles:['dokter'],separate_verifier:false}))});p=await policy('clinical_template',template);assert.equal(p.reviewed_by,f.worker);});
await check('clinical execution checks individual authority; admin and ungranted doctor denied',async()=>{const data={admission_id:1,policy_id:p.id,values:{observation:120},reason:'Synthetic clinical record'};await actor(f.receiver);await assert.rejects(()=>rpc('rs_clinical_command',['record',JSON.stringify(data),key()]),/Privilege/);await actor();await assert.rejects(()=>rpc('rs_clinical_command',['record',JSON.stringify(data),key()]),/Peran/);await actor(f.worker);record=await rpc('rs_clinical_command',['record',JSON.stringify(data),key()]);record=await rpc('rs_clinical_command',['sign',JSON.stringify({id:record.id,reason:'Synthetic clinical signature'}),key()]);assert.ok(record.signed_at);});
await check('episode handover requires both role authority and individual grant',async()=>{await policy('authority',{rules:[{action:'clinical.record',roles:['dokter'],separate_verifier:false},{action:'clinical.sign',roles:['dokter'],separate_verifier:false},{action:'episode.open',roles:['super_admin'],separate_verifier:false},{action:'clinical.episode.accept',roles:['dokter'],separate_verifier:false}]});await actor();const ep=await rpc('rs_episode_command',['open',JSON.stringify({admission_id:1,unit:'rs-igd-flow',physical_unit_id:1,cutover_at:new Date().toISOString(),reason:'Synthetic handover'}),key()]);await actor(f.worker);await assert.rejects(()=>rpc('rs_episode_command',['accept',JSON.stringify({id:ep.id,version:ep.version,reason:'Synthetic ungranted handover'}),key()]),/Privilege/);await actor();await approve('privilege',await cmd('privilege','create',{user_id:f.worker,scope:'rs-igd-flow',actions:['clinical.episode.accept'],credential_ids:[c.id],valid_from:from,valid_until:until,evidence:'Synthetic handover authority'}));await actor(f.worker);const accepted=await rpc('rs_episode_command',['accept',JSON.stringify({id:ep.id,version:ep.version,reason:'Synthetic granted handover'}),key()]);assert.equal(accepted.state,'active');assert.equal(accepted.accepted_by,f.worker);});
await check('expired credential and changed professional role fail closed',async()=>{await q('UPDATE ops_professional_credentials SET valid_until=$1 WHERE id=$2',[from,c.id]);await actor(f.worker);await assert.rejects(()=>q("SELECT ops_assert_individual_privilege('rs-igd-flow','clinical.sign')"),/Privilege/);await q('UPDATE ops_professional_credentials SET valid_until=$1 WHERE id=$2',[until,c.id]);await q("UPDATE user_profiles SET role='admin_faskes' WHERE id=$1",[f.worker]);await assert.rejects(()=>q("SELECT ops_assert_individual_privilege('rs-igd-flow','clinical.sign')"),/Profesi/);await q("UPDATE user_profiles SET role='dokter' WHERE id=$1",[f.worker]);});
await check('credential revocation immediately denies new clinical actions while signed history survives',async()=>{await actor(f.receiver);await cmd('credential','revoke',{id:c.id,version:c.version});await actor(f.worker);await assert.rejects(()=>rpc('rs_clinical_command',['record',JSON.stringify({admission_id:1,policy_id:p.id,values:{observation:121},reason:'Synthetic denied record'}),key()]),/Privilege/);assert.equal(new Date((await q('SELECT signed_at FROM rs_clinical_records WHERE id=$1',[record.id]))[0].signed_at).getTime(),new Date(record.signed_at).getTime());await actor();await assert.rejects(()=>rpc('ops_policy_command',[p.id,'activate',JSON.stringify({expected_state:'approved',reason:'Synthetic replay after revoked reviewer'}),key()]),/Privilege/);});
await check('non-governance professional board exposes only own credentials and privileges',async()=>{await q("UPDATE user_profiles SET role='nurse' WHERE id=$1",[f.receiver]);await actor(f.receiver);const board=await rpc('ops_workforce_board',['credential',0]);assert.equal(board.rows.length,0);assert.equal(board.credentials.length,0);await q("UPDATE user_profiles SET role='dokter' WHERE id=$1",[f.receiver]);});
await check('cross-tenant and direct mutation denied; old policy core cannot bypass gate',async()=>{await actor(f.foreign,f.B);await assert.rejects(()=>cmd('privilege','revoke',{id:g.id,version:g.version}),/tidak ditemukan/);await pg.exec('SET ROLE authenticated');assert.equal((await q('SELECT count(*)::int n FROM ops_individual_privileges'))[0].n,0);await assert.rejects(()=>q("UPDATE ops_professional_credentials SET state='verified'"),/permission denied/);await assert.rejects(()=>rpc('ops_policy_command_before_workforce',[null,'create','{}',key()]),/permission denied/);await pg.exec('RESET ROLE');});
}catch(e){error=e;}finally{if(pg){await pg.close();closed=true;}const out=path.join(__dirname,'../../docs/audit-evidence/2026-10-09');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'workforce-privileges-simulation.json'),JSON.stringify({synthetic:true,cleanup:{database_closed:closed,live_records_created:0},results,error:error?.message},null,2)+'\n');}if(error)throw error;})().catch(e=>{console.error(e);process.exitCode=1;});
