// OWNED_BY: generic. No-deposit source payment, refund, and replenishment.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const f=require('../lib/cashier-workflow-fixture.cjs'),{createBillingScenario}=require('../lib/billing-scenario.cjs');
let pg,error,closed=false,n=0;const results=[];
(async()=>{try{
 pg=await f.createCashierFixture();const s=await createBillingScenario(pg,{deposit_method:'none'}),invoice=await s.dischargeAndInvoice();
 const cash=(action,data)=>s.rpc('rs_cashier_command',[action,JSON.stringify({reason:'Synthetic direct payment evidence',...data}),`direct-payment-${++n}`]);
 async function post(kind,amount,receipt){await s.actor();let i=await cash('create',{setup_id:s.setup.id,invoice_id:invoice.id,receipt_id:receipt,kind,amount,event_key:'synthetic.deposit.'+kind,cost_center:'SYN-RI',payment_method:'Tunai',payment_ref:'SYN-DIRECT-'+n});await s.actor(f.receiver,'finance_staff');return cash('approve',{id:i.id,version:i.version});}
 const payment=await post('pay',200);assert.equal(Number((await s.rpc('rs_cashier_board',[s.setup.id,0])).invoices[0].balance),0);assert.equal((await s.q('SELECT count(*)::int n FROM cashier_transactions'))[0].n,1);results.push('none policy directly settles invoice with one cash/receivable journal');
 await assert.rejects(()=>s.rpc('rs_invoice_command',['void',JSON.stringify({id:invoice.id,version:invoice.version,reason:'Synthetic void blocked'}),'direct-void-blocked']),/Void alokasi/);results.push('invoice reversal cannot abandon an active cash payment');
 await post('refund_payment',50,payment.id);assert.equal(Number((await s.rpc('rs_cashier_board',[s.setup.id,0])).invoices[0].balance),50);await s.actor();let excess=await cash('create',{setup_id:s.setup.id,invoice_id:invoice.id,receipt_id:payment.id,kind:'refund_payment',amount:151,event_key:'synthetic.deposit.refund_payment',cost_center:'SYN-RI',payment_method:'Tunai',payment_ref:'SYN-EXCESS'});await s.actor(f.receiver,'finance_staff');await assert.rejects(()=>cash('approve',{id:excess.id,version:excess.version}),/Saldo receipt/);results.push('payment refund restores receivable and cannot exceed original net receipt');
 await post('pay',50);const board=await s.rpc('rs_cashier_board',[s.setup.id,0]);assert.equal(Number(board.invoices[0].balance),0);assert.equal(Number(board.setups[0].received),0);assert.equal(Number((await s.q("SELECT sum(debit-credit) balance FROM journal_lines WHERE account_code='1-1100'"))[0].balance),200);assert.equal(Number((await s.q("SELECT sum(debit-credit) balance FROM journal_lines WHERE account_code='1-1300'"))[0].balance),0);assert.equal((await s.q('SELECT count(*)::int n FROM cashier_transactions'))[0].n,3);results.push('replenishment reconciles source cash 200, receivable zero and deposit zero');
 for(const name of results)console.log('PASS '+name);
}catch(e){error=e;}finally{if(pg){await pg.close();closed=true;}const dir=path.resolve(__dirname,'../../docs/audit-evidence/2026-10-10');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'inpatient-direct-payment.json'),JSON.stringify({synthetic:true,results,cleanup:{database_closed:closed,live_records_created:0},error:error?.message},null,2)+'\n');}if(error)throw error;})().catch(e=>{console.error(e);process.exitCode=1;});
