// OWNED_BY: generic. These commands record operations, never perform deployment.
let techOpsPage='tech-isu',techOpsOffset=0,techOpsEpoch=0,techOpsData;
const techOpsEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const techOpsDefinitions={'tech-isu':{kind:'ticket',title:'Tiket & Tindak Lanjut',create:'create'},'tech-roadmap':{kind:'change',title:'Rilis & Perubahan',create:'create'},'tech-modul':{kind:'deployment',title:'Modul & Versi Instalasi',create:'report'}};
function techOpsActions(row,kind){return kind==='ticket'?({OPEN:['triage'],TRIAGED:['start'],IN_PROGRESS:['wait','resolve'],WAITING_CLIENT:['start'],RESOLVED:['close','reopen'],CLOSED:['reopen']}[row.status]||[]):kind==='change'?({DRAFT:['submit'],REVIEW:['approve','reject'],APPROVED:['start'],RUNNING:['complete','rollback'],SUCCEEDED:['rollback']}[row.status]||[]):({reported:['verify','revoke'],verified:['revoke']}[row.state]||[]);}
const techOpsActionLabels={create:'Buat',report:'Laporkan versi instalasi',triage:'Triage / tugaskan',start:'Mulai',wait:'Tunggu pelanggan',resolve:'Selesaikan',close:'Verifikasi & tutup',reopen:'Buka kembali',submit:'Ajukan review',approve:'Setujui',reject:'Tolak',complete:'Catat berhasil',rollback:'Catat rollback',verify:'Verifikasi instalasi',revoke:'Cabut pengesahan'};
async function renderTechOperations(params={}){if(params.page&&params.page!==techOpsPage){techOpsPage=params.page;techOpsOffset=0;}const config=techOpsDefinitions[techOpsPage];if(!config)throw Error('Halaman operasi Tech tidak valid');const epoch=++techOpsEpoch,main=document.getElementById('main-content');main.innerHTML='<h1>'+config.title+'</h1><p>Memuat…</p>';
try{const data=await sbRpc('tech_ops_board',{p_kind:config.kind,p_offset:techOpsOffset});if(epoch!==techOpsEpoch||(typeof currentPage==='string'&&currentPage!==techOpsPage))return;techOpsData=data;
main.innerHTML=`<section class="tech-ops"><style>.tech-ops{max-width:1100px;margin:auto;padding:16px}.tech-ops article,.tech-ops form{border:1px solid #bccbd5;border-radius:8px;padding:16px;margin:12px 0}.tech-ops label{display:block;margin:12px 0}.tech-ops input,.tech-ops select,.tech-ops textarea{padding:9px;width:100%;box-sizing:border-box}.tech-ops button{padding:9px;margin:4px}.tech-ops pre{white-space:pre-wrap;overflow-wrap:anywhere}</style><h1>${config.title}</h1><p>${config.kind==='deployment'?'Versi instalasi berasal dari rilis sukses yang dilaporkan dan diverifikasi petugas berbeda. Pengesahan ini berbasis bukti manual; koneksi/versi live tidak dianggap tersedia tanpa sumber telemetri.':config.kind==='change'?'Perubahan melalui review terpisah, preflight, bukti hasil dan rollback. Pencatatan ini tidak menjalankan deploy.':'Triage → penugasan → penanganan → bukti penyelesaian → verifikasi oleh petugas berbeda. Riwayat dan pembukaan ulang tersimpan.'}</p><button id="to-new">${techOpsActionLabels[config.create]}</button><button id="to-reload">Muat ulang</button><p id="to-error" role="alert"></p><div id="to-editor"></div>${data.rows.slice(0,50).map(row=>`<article><h2>${techOpsEsc(row.title||row.module_key)} · #${row.id}</h2><p>${techOpsEsc(row.status||row.state)} · v${row.ops_version}</p><p>${techOpsEsc(row.description||row.risk||row.installation_id)}</p>${config.kind==='deployment'?`<p>${techOpsEsc(row.release_version)} · ${techOpsEsc(row.environment)} · Rilis #${row.change_id}</p><p>${techOpsEsc(row.evidence)}</p>`:config.kind==='ticket'?`<p>${techOpsEsc(row.priority)} · Pemilik: ${techOpsEsc(data.staff.find(s=>s.id===row.owner_user_id)?.name||'Belum ditugaskan')}</p><p>${techOpsEsc(row.resolution||'')}</p>`:`<p>Rollback: ${techOpsEsc(row.rollback_plan)}</p><p>Versi: ${techOpsEsc(row.release_version||'Belum dirilis')}</p>`}${techOpsActions(row,config.kind).map(a=>`<button data-id="${row.id}" data-action="${a}">${techOpsActionLabels[a]}</button>`).join('')}</article>`).join('')||'<p>Belum ada catatan tenant yang dapat diakses.</p>'}<nav><button id="to-prev" ${techOpsOffset===0?'disabled':''}>Sebelumnya</button> Halaman ${1+techOpsOffset/50} <button id="to-next" ${data.rows.length<=50?'disabled':''}>Berikutnya</button></nav></section>`;
document.getElementById('to-new').onclick=()=>techOpsForm(config.kind,config.create);document.getElementById('to-reload').onclick=()=>renderTechOperations();document.getElementById('to-prev').onclick=()=>{techOpsOffset=Math.max(0,techOpsOffset-50);renderTechOperations();};document.getElementById('to-next').onclick=()=>{techOpsOffset+=50;renderTechOperations();};main.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>techOpsForm(config.kind,b.dataset.action,data.rows.find(r=>r.id===Number(b.dataset.id))));
}catch(e){if(epoch===techOpsEpoch&&(typeof currentPage!=='string'||currentPage===techOpsPage)){main.innerHTML=`<h1>${config.title}</h1><p role="alert">${techOpsEsc(e.message)}</p><button id="to-retry">Coba lagi</button>`;document.getElementById('to-retry').onclick=()=>renderTechOperations();}}
}
function techOpsForm(kind,action,row){const input=(label,name,type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" ${extra} required></label>`,text=(label,name)=>`<label>${label}<textarea name="${name}" required minlength="3"></textarea></label>`,select=(label,name,values)=>`<label>${label}<select name="${name}" required><option value="">Pilih</option>${values.map(([v,l])=>`<option value="${techOpsEsc(v)}">${techOpsEsc(l)}</option>`).join('')}</select></label>`;let fields='';
if(action==='create'){fields=input('Judul','title','text','maxlength="200"');if(kind==='ticket')fields+=text('Uraian masalah','description')+select('Prioritas','priority',['P0','P1','P2','P3'].map(v=>[v,v]));else fields+=select('Jenis','type',['code','config','schema','secret','infrastructure','content'].map(v=>[v,v]))+text('Risiko','risk')+text('Rencana rollback','rollback');}
if(action==='triage')fields+=select('Pemilik tugas','owner',techOpsData.staff.map(s=>[s.id,s.name+' · '+s.role]));if(action==='resolve')fields+=text('Penyelesaian dan referensi bukti','resolution');if(action==='start'&&kind==='change')fields+=text('Referensi hasil preflight','preflight');if(['complete','rollback'].includes(action)&&kind==='change')fields+=text('Referensi bukti hasil','result');if(action==='complete')fields+=input('Versi rilis','release','text','maxlength="100"');
if(action==='report')fields+=input('ID perubahan sukses','change_id','number','min="1" step="1"')+input('Kode modul','module','text','pattern="[a-z][a-z0-9-]*"')+input('ID instalasi','installation','text','maxlength="200"')+input('Versi rilis','release','text','maxlength="100"')+select('Environment','environment',['test','staging','production'].map(v=>[v,v]))+text('Referensi bukti instalasi','evidence');if(action==='verify')fields+=text('Referensi verifikasi instalasi','evidence');
const target=document.getElementById('to-editor');target.innerHTML=`<form><h2>${techOpsActionLabels[action]}${row?' #'+row.id:''}</h2>${fields}${text('Alasan','reason')}<button type="submit">Simpan</button><button type="button" id="to-cancel">Tutup</button></form>`;const form=target.querySelector('form'),key=crypto.randomUUID();document.getElementById('to-cancel').onclick=()=>target.replaceChildren();form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;try{const d=new FormData(form),data=Object.fromEntries(d);if(row){data.id=row.id;data.version=row.ops_version;}if(data.change_id)data.change_id=Number(data.change_id);if(data.preflight)data.preflight={reference:data.preflight};if(data.result)data.result={reference:data.result};await sbRpc('tech_ops_command',{p_kind:kind,p_action:action,p_data:data,p_key:key});if(form.isConnected)await renderTechOperations();}catch(error){const out=document.getElementById('to-error');if(out)out.textContent=error.message;}finally{if(button.isConnected)button.disabled=false;}};target.scrollIntoView({block:'start'});
}
window.renderTechOperations=renderTechOperations;
