// OWNED_BY: generic. Slot allocation is distinct from clinical completion.
let rsBookingSetup=null,rsBookingRows=[],rsBookingEpoch=0,rsBookingOffset=0;
const rsBookingEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function renderResourceBooking(){
 const epoch=++rsBookingEpoch,main=document.getElementById('main-content');main.innerHTML='<section><h1>Booking Sumber Daya</h1><p>Memuat jadwal…</p></section>';
 try{
  const [setup,board]=await Promise.all([sbRpc('rs_booking_setup',{}),sbRpc('rs_booking_board',{p_offset:rsBookingOffset})]);const rows=board.bookings;
  if(epoch!==rsBookingEpoch||(typeof currentPage==='string'&&currentPage!=='rs-resource-booking'))return;rsBookingSetup=setup;rsBookingRows=rows;
  main.innerHTML=`<section class="rs-booking"><style>.rs-booking{max-width:1100px;margin:auto;padding:16px}.rs-booking article,.rs-booking form{border:1px solid #bccbd5;padding:16px;margin:12px 0;border-radius:8px}.rs-booking label{display:block;margin:10px 0}.rs-booking input,.rs-booking select,.rs-booking textarea{padding:9px;max-width:100%;box-sizing:border-box}.rs-booking button{padding:9px;margin:4px}.rs-booking fieldset{margin:10px 0}.rs-booking .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:12px}</style><h1>Booking Sumber Daya</h1><p>Ruang/mesin dialokasikan bersama secara atomik. Buffer dan layanan yang masih berjalan tetap memblokir kapasitas. Selesai booking berarti penggunaan resource selesai, bukan pengesahan tindakan klinis.</p><p id="rb-error" role="alert"></p><button id="rb-new">Reservasi</button><button id="rb-setup">Setup sumber daya</button><button id="rb-reload">Muat ulang</button><div id="rb-editor"></div><div class="grid">${rows.slice(0,50).map(b=>{const expired=b.state==='reserved'&&new Date(b.expires_at)<=new Date();const actions=expired?['expire']:({reserved:['confirm','cancel'],confirmed:['start','cancel'],in_progress:['complete']}[b.state]||[]);return `<article><h2>${rsBookingEscape(setup.workflows.find(w=>w.code===b.scope)?.label||b.scope)}</h2><p>#${b.id} · ${rsBookingEscape(b.purpose)} · ${expired?'Reservasi kedaluwarsa':rsBookingEscape(b.state)}</p><p>${rsBookingEscape(new Date(b.starts_at).toLocaleString('id-ID'))} – ${rsBookingEscape(new Date(b.ends_at).toLocaleString('id-ID'))}</p><p>Order ${b.order_id??'—'} · Versi kebijakan #${b.policy_id}</p>${actions.map(a=>`<button data-booking="${b.id}" data-action="${a}">${({confirm:'Konfirmasi',cancel:'Batalkan',start:'Mulai penggunaan',complete:'Selesaikan penggunaan',expire:'Tutup kedaluwarsa'})[a]}</button>`).join('')}</article>`;}).join('')||'<p>Belum ada booking yang dapat diakses.</p>'}</div><nav><button id="rb-prev" ${rsBookingOffset===0?'disabled':''}>Sebelumnya</button><span>Halaman ${1+rsBookingOffset/50}</span><button id="rb-next" ${rows.length<=50?'disabled':''}>Berikutnya</button></nav></section>`;
  document.getElementById('rb-new').onclick=rsBookingNew;document.getElementById('rb-setup').onclick=()=>navigate('cfg-rs-policy');document.getElementById('rb-reload').onclick=renderResourceBooking;
  const cards=main.querySelectorAll('.grid article');rows.slice(0,50).forEach((b,index)=>{const line=document.createElement('p');line.className='rb-assigned';line.textContent=board.items.filter(i=>i.booking_id===b.id).map(i=>`${i.resource_name}: ${i.units} unit`).join(' · ');cards[index].appendChild(line);});
  document.getElementById('rb-prev').onclick=()=>{rsBookingOffset=Math.max(0,rsBookingOffset-50);renderResourceBooking();};document.getElementById('rb-next').onclick=()=>{rsBookingOffset+=50;renderResourceBooking();};
  main.querySelectorAll('[data-booking]').forEach(button=>button.onclick=()=>rsBookingTransition(rows.find(b=>b.id===Number(button.dataset.booking)),button.dataset.action));
 }catch(e){if(epoch===rsBookingEpoch&&(typeof currentPage!=='string'||currentPage==='rs-resource-booking')){main.innerHTML=`<section><h1>Booking belum dapat dibaca</h1><p role="alert">${rsBookingEscape(e.message)}</p><p>Periksa migrasi 0077, master aktif dan hak akses.</p><button id="rb-retry">Coba lagi</button></section>`;document.getElementById('rb-retry').onclick=renderResourceBooking;}}
}
function rsBookingForm(html,save){
 const editor=document.getElementById('rb-editor');editor.innerHTML=`<form>${html}<label>Alasan<textarea name="reason" minlength="3" required></textarea></label><button type="submit">Simpan</button><button type="button" id="rb-close">Tutup</button></form>`;const form=editor.querySelector('form'),key=crypto.randomUUID();
 document.getElementById('rb-close').onclick=()=>editor.replaceChildren();form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;try{await save(new FormData(form),key);if(form.isConnected)await renderResourceBooking();}catch(error){const output=document.getElementById('rb-error');if(output)output.textContent=error.message;}finally{if(button.isConnected)button.disabled=false;}};editor.scrollIntoView({block:'start'});
}
function rsBookingNew(){
 rsBookingForm(`<h2>Reservasi multi-resource</h2><label>Unit layanan<select name="scope" id="rb-scope" required><option value="">Pilih</option>${rsBookingSetup.policies.map(p=>`<option value="${rsBookingEscape(p.scope)}">${rsBookingEscape(rsBookingSetup.workflows.find(w=>w.code===p.scope)?.label||p.scope)} · v${p.revision}</option>`).join('')}</select></label><label>Keperluan<select name="purpose" id="rb-purpose" required><option value="service">Pelayanan dari order</option><option value="maintenance">Pemeliharaan</option></select></label><div id="rb-order"></div><label>Mulai<input type="datetime-local" name="start" required></label><label>Selesai<input type="datetime-local" name="end" required></label><div id="rb-resources"></div>`,async(d,key)=>{
  const order=d.get('purpose')==='service'?rsBookingSetup.orders.find(o=>o.id===Number(d.get('order'))):null;if(d.get('purpose')==='service'&&!order)throw Error('Pilih order sumber aktif');
  const resources=d.getAll('resource').map(id=>({master_id:Number(id),units:Number(d.get('units_'+id))}));
  if(!resources.length)throw Error('Pilih minimal satu sumber daya');
  await sbRpc('rs_booking_command',{p_action:'reserve',p_data:{scope:d.get('scope'),purpose:d.get('purpose'),admission_id:order?.admission_id??null,order_id:order?.id??null,starts_at:new Date(d.get('start')).toISOString(),ends_at:new Date(d.get('end')).toISOString(),resources,reason:d.get('reason')},p_request_key:key});
 });
 document.getElementById('rb-scope').onchange=rsBookingFields;document.getElementById('rb-purpose').onchange=rsBookingFields;rsBookingFields();
}
function rsBookingFields(){
 const scope=document.getElementById('rb-scope').value,p=rsBookingSetup.policies.find(p=>p.scope===scope),service=document.getElementById('rb-purpose').value==='service';
 document.getElementById('rb-order').innerHTML=service?`<label>Order aktif (200 terbaru yang dapat diakses)<select name="order" required><option value="">Pilih</option>${rsBookingSetup.orders.filter(o=>o.kind===scope).map(o=>`<option value="${o.id}">#${o.id} ${rsBookingEscape(o.title)}</option>`).join('')}</select></label>`:'';
 document.getElementById('rb-resources').innerHTML=p?p.payload.resources.map(r=>{const master=rsBookingSetup.resources.find(x=>x.id===r.master_id);return `<fieldset><legend><label><input type="checkbox" name="resource" value="${r.master_id}"> ${rsBookingEscape(master?.name||'Resource tidak aktif')}</label></legend><label>Unit kapasitas<input name="units_${r.master_id}" type="number" min="1" max="${Math.min(r.capacity,master?.capacity||0)}" step="1"></label><small>Buffer ${r.buffer_before_minutes} menit sebelum / ${r.buffer_after_minutes} menit sesudah.</small></fieldset>`;}).join(''):'<p>Pilih kebijakan unit yang sudah disahkan.</p>';
 const target=document.getElementById('rb-resources');target.querySelectorAll('[name=resource]').forEach(box=>{const input=target.querySelector(`[name=units_${box.value}]`);input.disabled=true;box.onchange=()=>{input.disabled=!box.checked;input.required=box.checked;};});
}
function rsBookingTransition(b,action){rsBookingForm(`<h2>${rsBookingEscape(action)} booking #${b.id}</h2><p>Transisi dan kewenangan diperiksa server.</p>`,async(d,key)=>sbRpc('rs_booking_command',{p_action:action,p_data:{id:b.id,version:b.version,reason:d.get('reason')},p_request_key:key}));}
window.renderResourceBooking=renderResourceBooking;
