// OWNED_BY: generic. Existing inventory master/batch/ledger are the source.
let rsStockData,rsStockOffset=0,rsStockEpoch=0;
const rsStockEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function renderSharedStock(){
 const epoch=++rsStockEpoch,main=document.getElementById('main-content');main.innerHTML='<h1>Stok Antarunit RS</h1><p>Memuat lot…</p>';
 try{const data=await sbRpc('rs_stock_setup',{p_offset:rsStockOffset});if(epoch!==rsStockEpoch||(typeof currentPage==='string'&&currentPage!=='rs-shared-stock'))return;rsStockData=data;
 main.innerHTML=`<section class="rs-stock"><style>.rs-stock{max-width:1100px;margin:auto;padding:16px}.rs-stock article,.rs-stock form{border:1px solid #bccbd5;border-radius:8px;padding:16px;margin:12px 0}.rs-stock label{display:block;margin:10px 0}.rs-stock input,.rs-stock select,.rs-stock textarea{padding:8px;max-width:100%;box-sizing:border-box}.rs-stock button{padding:8px;margin:4px}.rs-stock table{width:100%;font-size:14px}.rs-stock .scroll{overflow:auto}</style><h1>Stok Antarunit RS</h1><p>Saldo memakai master persediaan dan ledger sumber. Opening lot harus disahkan melalui Kebijakan Operasional. Farmasi mempunyai sumber tersendiri dan belum terhubung ke modul ini.</p><button id="ss-policy">Review kebijakan</button><p id="ss-error" role="alert"></p><div id="ss-editor"></div>${data.batches.slice(0,50).map(b=>`<article><h2>${rsStockEscape(b.item_name)} · ${rsStockEscape(b.batch_no)}</h2><p>Lot #${b.id} · Saldo ${rsStockEscape(b.qty_remaining)} · Expiry ${rsStockEscape(b.expiry_date||'Belum ditetapkan')} · ${rsStockEscape(b.domain||'Belum opening')}</p>${data.positions.filter(p=>p.batch_id===b.id).map(p=>`<p>${rsStockEscape(data.warehouses.find(w=>w.id===p.warehouse_id)?.name||p.warehouse_id)} · ${rsStockEscape(p.state)}: ${rsStockEscape(p.qty)}</p>`).join('')}<button data-lot="${b.id}" data-action="draft">Rancang opening / rekonsiliasi</button>${(b.domain?['reconcile','receive','issue','return','transfer','quarantine','release','waste','link_order']:['initialize']).map(a=>`<button data-lot="${b.id}" data-action="${a}">${({reconcile:'Terapkan rekonsiliasi',receive:'Terima',issue:'Keluarkan',return:'Retur',transfer:'Transfer',quarantine:'Karantina',release:'Lepas karantina',waste:'Afkir',link_order:'Hubungkan order mutu',initialize:'Terapkan opening'})[a]}</button>`).join('')}</article>`).join('')||'<p>Belum ada batch dari master persediaan tenant.</p>'}<nav><button id="ss-prev" ${rsStockOffset===0?'disabled':''}>Sebelumnya</button> Halaman ${1+rsStockOffset/50} <button id="ss-next" ${data.batches.length<=50?'disabled':''}>Berikutnya</button></nav><h2>Jejak ledger (100 terbaru pada halaman ini)</h2><div class="scroll"><table><thead><tr><th>ID</th><th>Lot</th><th>Aksi</th><th>Delta posisi</th><th>Status</th><th>Alasan</th></tr></thead><tbody>${data.ledger.map(l=>`<tr><td>${l.id}</td><td>${l.rs_batch_id}</td><td>${rsStockEscape(l.rs_operation)}</td><td>${rsStockEscape(l.rs_qty_delta)}</td><td>${rsStockEscape(l.rs_state)}</td><td>${rsStockEscape(l.notes)}</td></tr>`).join('')}</tbody></table></div></section>`;
 document.getElementById('ss-policy').onclick=()=>navigate('cfg-rs-policy');const mappingButton=document.createElement('button');mappingButton.textContent='Rancang pemetaan sumber lama';mappingButton.onclick=rsStockOwnershipForm;document.getElementById('ss-policy').after(mappingButton);document.getElementById('ss-prev').onclick=()=>{rsStockOffset=Math.max(0,rsStockOffset-50);renderSharedStock();};document.getElementById('ss-next').onclick=()=>{rsStockOffset+=50;renderSharedStock();};main.querySelectorAll('[data-lot]').forEach(btn=>btn.onclick=()=>rsStockForm(data.batches.find(b=>b.id===Number(btn.dataset.lot)),btn.dataset.action));
 }catch(e){if(epoch===rsStockEpoch&&(typeof currentPage!=='string'||currentPage==='rs-shared-stock'))main.innerHTML=`<h1>Stok belum dapat dibaca</h1><p role="alert">${rsStockEscape(e.message)}</p><p>Periksa migrasi 0078 dan hak akses.</p>`;}
}
function rsStockForm(batch,action){
 const input=(label,name,type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" ${extra} required></label>`;
 const warehouse=name=>`<label>${name==='destination'?'Lokasi tujuan':'Lokasi sumber'}<select name="${name}" required><option value="">Pilih</option>${rsStockData.warehouses.map(w=>`<option value="${w.id}">${rsStockEscape(w.name)}</option>`).join('')}</select></label>`;
 const scope={blood:'rs-transfusion',cssd:'rs-cssd',linen:'rs-linen',diet:'rs-diet'}[batch.domain];
 const editor=document.getElementById('ss-editor');let fields=scope?`<input type="hidden" name="scope" value="${scope}">`:input('Scope unit (kode menu)','scope');
 if(action==='draft')fields='<label>Domain<select name="domain" required><option value="">Pilih</option><option value="general">Umum</option><option value="linen">Linen</option><option value="diet">Diet</option><option value="cssd">CSSD</option><option value="blood">Bank darah</option></select></label>'+input('Timezone IANA','timezone')+'<p>Isi hanya lokasi yang mempunyai saldo opening. Total wajib sama dengan saldo sumber lot.</p>'+rsStockData.warehouses.map(w=>`<fieldset><legend><label><input type="checkbox" name="location" value="${w.id}">${rsStockEscape(w.name)}</label></legend>${input('Tersedia','available_'+w.id,'number','min="0" step="any"')}${input('Karantina','quarantine_'+w.id,'number','min="0" step="any"')}</fieldset>`).join('');
 else if(!['initialize','reconcile','link_order'].includes(action)){fields+=warehouse('warehouse')+input('Jumlah','qty','number','min="0.000001" step="any"');if(action==='transfer')fields+=warehouse('destination');if(['receive','return','waste'].includes(action))fields+='<label>Status<select name="state" required><option value="">Pilih</option><option value="available">Tersedia</option><option value="quarantine">Karantina</option></select></label>';fields+='<label>ID kunjungan (jika terkait pasien)<input name="admission" type="number" min="1"></label><label>ID order layanan (jika terkait)<input name="order" type="number" min="1"></label>';if(action==='return')fields+=input('ID ledger pengeluaran asal','return_of','number','min="1"');if(action==='release'&&['blood','cssd'].includes(batch.domain))fields+=input('ID order mutu selesai','quality_order','number','min="1"');if(action==='issue'&&batch.domain==='blood')fields+=input('ID formulir verifikasi transfusi ditandatangani','clinical','number','min="1"');}
 else if(action==='link_order')fields+=input('ID order mutu aktif','order','number','min="1"');
 editor.innerHTML=`<form><h2>${rsStockEscape(action)} lot #${batch.id}</h2>${fields}<label>Alasan<textarea name="reason" required minlength="3"></textarea></label><button type="submit">Simpan</button><button type="button" id="ss-close">Tutup</button></form>`;
 const form=editor.querySelector('form'),key=crypto.randomUUID();document.getElementById('ss-close').onclick=()=>editor.replaceChildren();
 if(action==='draft')form.querySelectorAll('[name=location]').forEach(box=>{const inputs=box.closest('fieldset').querySelectorAll('input[type=number]');inputs.forEach(i=>{i.disabled=true;});box.onchange=()=>inputs.forEach(i=>{i.disabled=!box.checked;});});
 form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('[type=submit]');if(btn.disabled)return;btn.disabled=true;try{const d=new FormData(form);
 if(action==='draft'){const positions=d.getAll('location').flatMap(id=>['available','quarantine'].map(state=>({warehouse_id:Number(id),state,qty:Number(d.get(state+'_'+id))})));if(!positions.length)throw Error('Pilih minimal satu lokasi');await sbRpc('ops_policy_command',{p_id:null,p_action:'create',p_data:{kind:'stock_opening',scope:'stock-lot:'+batch.id,payload:{batch_id:batch.id,domain:d.get('domain'),timezone:d.get('timezone'),positions},reason:d.get('reason')},p_request_key:key});}
 else{const data={batch_id:batch.id,scope:d.get('scope'),reason:d.get('reason')};for(const [field,name] of [['qty','qty'],['warehouse_id','warehouse'],['destination_id','destination'],['admission_id','admission'],['order_id','order'],['return_of','return_of'],['quality_order_id','quality_order'],['clinical_record_id','clinical']])if(d.get(name))data[field]=Number(d.get(name));if(d.get('state'))data.state=d.get('state');await sbRpc('rs_stock_command',{p_action:action,p_data:data,p_request_key:key});}
 if(form.isConnected)await renderSharedStock();}catch(error){const out=document.getElementById('ss-error');if(out)out.textContent=error.message;}finally{if(btn.isConnected)btn.disabled=false;}};editor.scrollIntoView({block:'start'});
}
window.renderSharedStock=renderSharedStock;
function rsStockOwnershipForm(){
 const target=document.getElementById('ss-editor');target.innerHTML='<form><h2>Pemetaan ownership sumber lama</h2><p>Hanya administrator. Pastikan daftar ID ditinjau terhadap inventaris sumber. Persetujuan pihak berbeda wajib sebelum diterapkan. ID dan nilai master tetap utuh.</p><label>Lingkup review<input name="scope" required maxlength="100"></label><label>ID item, dipisahkan koma<input name="items"></label><label>ID gudang, dipisahkan koma<input name="warehouses"></label><label>Alasan<textarea name="reason" minlength="3" required></textarea></label><button type="submit">Buat draft review</button></form>';
 const form=target.querySelector('form'),key=crypto.randomUUID();form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');if(button.disabled)return;button.disabled=true;try{const d=new FormData(form),sources=[['item','items'],['warehouse','warehouses']].flatMap(([kind,field])=>String(d.get(field)||'').split(',').map(v=>v.trim()).filter(Boolean).map(v=>{if(!/^[1-9][0-9]*$/.test(v)||!Number.isSafeInteger(Number(v)))throw Error('ID sumber harus bilangan bulat positif');return {kind,id:Number(v)};}));if(!sources.length)throw Error('Isi minimal satu sumber');await sbRpc('ops_policy_command',{p_id:null,p_action:'create',p_data:{kind:'stock_ownership',scope:d.get('scope'),payload:{sources},reason:d.get('reason')},p_request_key:key});if(form.isConnected)await renderSharedStock();}catch(error){const out=document.getElementById('ss-error');if(out)out.textContent=error.message;}finally{if(button.isConnected)button.disabled=false;}};
}
