-- DEPRECATED — jangan jalankan file legacy ini.
--
-- Provisioning akun sekarang berada di:
--   db/migrations/0069_rbac_user_provisioning.sql
--
-- Migration tersebut menggantikan RPC lama dengan validasi actor Super Admin,
-- isolasi tenant, hash password tanpa fallback plaintext, dan grant yang tidak
-- lagi membuka fungsi kepada anon. Jalankan migration 0069 di staging sesuai
-- runbook database sebelum mengaktifkan tombol pembuatan akun.
